PCA IMPLEMENTATION

In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [14]:
x = np.array([[1,1], [2,1], [3,2], [-1, -1], [-2,-1], [-3, -2]])
 

In [15]:
pca1 = PCA(n_components=1)  #instance of the PCA class
pca1.fit(x)
print(pca1.explained_variance_ratio_)   #99.2 percent of data spread is preserved in the principal component

x_transformed = pca1.transform(x)
print(x_transformed)

[0.99244289]
[[ 1.38340578]
 [ 2.22189802]
 [ 3.6053038 ]
 [-1.38340578]
 [-2.22189802]
 [-3.6053038 ]]


In [16]:
x_ = pca1.inverse_transform(x_transformed)    #performs the reconstruction step which gives back an appproximate value
#of the initial points in 2d
print(x_)

[[ 1.15997501  0.75383654]
 [ 1.86304424  1.21074232]
 [ 3.02301925  1.96457886]
 [-1.15997501 -0.75383654]
 [-1.86304424 -1.21074232]
 [-3.02301925 -1.96457886]]


In [17]:
#letting there be 2 principal components
pca2 = PCA(n_components=2)
pca2.fit(x)
print(pca2.explained_variance_ratio_)   #the first principal component captures almost all of the data spread whereas
#the second one is just perperdicular to the first one hence has a very low variance

x_transformed_1 = pca2.transform(x)
print(x_transformed_1)  

[0.99244289 0.00755711]
[[ 1.38340578  0.2935787 ]
 [ 2.22189802 -0.25133484]
 [ 3.6053038   0.04224385]
 [-1.38340578 -0.2935787 ]
 [-2.22189802  0.25133484]
 [-3.6053038  -0.04224385]]


In [18]:
x__ = pca2.inverse_transform(x_transformed_1)
print(x__)  #gives the exact value back, hence performing the reconstruction step from n axes to n axes gives the same 
#initial points back

[[ 1.  1.]
 [ 2.  1.]
 [ 3.  2.]
 [-1. -1.]
 [-2. -1.]
 [-3. -2.]]
