In [2]:
import numpy as np
import pandas as pd

In [3]:
x = np.arange(0,20,1)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
X = x.reshape(-1, 1)  #only 1 feature but multiple egs of that feature
print(X)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [5]:
y = 1 + x**2
print(y)

[  1   2   5  10  17  26  37  50  65  82 101 122 145 170 197 226 257 290
 325 362]


In [6]:
#@ in np is used for traditional matrix multiplication or dot prod in case of vectors

In [7]:
a = np.array([1,2])
b = np.array([3,4])
print(a@b)

11


In [8]:
a = np.array([[[2,3], [4,5]]])
b = np.array([[[2,3], [4,5]]])
print(a@b)

#even in case of higher order tensors, it does it based on normal matrix mult

[[[16 21]
  [28 37]]]


In [15]:
X = np.c_[x, x**2, x**3]   #engineering 3 new features which can be used for polynomial regression 
print(X)

[[   0    0    0]
 [   1    1    1]
 [   2    4    8]
 [   3    9   27]
 [   4   16   64]
 [   5   25  125]
 [   6   36  216]
 [   7   49  343]
 [   8   64  512]
 [   9   81  729]
 [  10  100 1000]
 [  11  121 1331]
 [  12  144 1728]
 [  13  169 2197]
 [  14  196 2744]
 [  15  225 3375]
 [  16  256 4096]
 [  17  289 4913]
 [  18  324 5832]
 [  19  361 6859]]


In [10]:
#np.ptp(2nd order tensor) finds the max peak to peak value bw cols 