In [1]:
#doing the same thing as in L5 but with sklearn module

In [5]:
import numpy as np
from sklearn.linear_model import SGDRegressor    #for the gradient descent, here stochastic is used 
from sklearn.preprocessing import StandardScaler   #for the initial feature scaling
import matplotlib.pyplot as plt 
import pandas as pd

In [6]:
df = pd.read_csv('C:\\Users\\Lenovo\\OneDrive\\Desktop\\coursera_ml\\data2.csv')
arr = df.to_numpy()
print(arr)

m = arr.shape[0]   #no of rows
n = arr.shape[1]-1  #no of features
print(m, n)

[[2104    5    1   45  460]
 [1416    3    2   40  232]
 [ 852    2    1   35  178]]
3 4


In [7]:
x_train = []
y_train = []

for i in range(m):
    x_train.append(arr[i][:n])
    y_train.append(arr[i][n])

x_train = np.array(x_train)
y_train = np.array(y_train)
print(x_train)
print(y_train)


[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


In [8]:
x_features = ['Size(sqft)','Number_of_Bedrooms','Number_of_floors','Age_of_Home']

scaling the features 


In [9]:
scale = StandardScaler()  #creating an instance of the StandardScalar class
x_norm = scale.fit_transform(x_train)   #performs z score normalisation

In [10]:
print(x_norm)

[[ 1.26311506  1.33630621 -0.70710678  1.22474487]
 [-0.08073519 -0.26726124  1.41421356  0.        ]
 [-1.18237987 -1.06904497 -0.70710678 -1.22474487]]


creating, fitting the model

In [11]:
sgdr = SGDRegressor(max_iter=4000)  #max_iter is not an indication of number of epochs to be completed
sgdr.fit(x_norm, y_train)   #same as calling the linear_regr function in L5 
print(sgdr)
print(f"number of epochs completed: {sgdr.n_iter_}, number of weight updates: {sgdr.t_}")

SGDRegressor(max_iter=4000)
number of epochs completed: 1239, number of weight updates: 3718.0


In [12]:
w = sgdr.intercept_
b = sgdr.coef_
print(w)
print(b)

[289.50567562]
[ 38.0527188   41.53885531 -30.94750412  36.34524978]


In [13]:
# very close the the w and b values from L5 using custom linear regr model 

In [14]:
y_pred = sgdr.predict(x_norm)
print(y_pred)

[459.47611651 231.56537604 177.47553429]
