FROM THIS LAB ONWARDS WE TALK ABOUT CLASSIFICATION

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y = np.array([0, 0, 0, 1, 1, 1])

print(x)
print(y)

[[0.5 1.5]
 [1.  1. ]
 [1.5 0.5]
 [3.  0.5]
 [2.  2. ]
 [1.  2.5]]
[0 0 0 1 1 1]


In [3]:
#plotting a scatterplot of the feature space
x_1 = []  #  values of features for which output is 1
x_0 = []  # values of feautres for which output is 0

for i in range(6):
    if y[i] == 1:
        x_1.append(x[i])
    else:
        x_0.append(x[i])

x_1 = np.array(x_1)
x_0 = np.array(x_0)
print(x_1)
print(x_0)

[[3.  0.5]
 [2.  2. ]
 [1.  2.5]]
[[0.5 1.5]
 [1.  1. ]
 [1.5 0.5]]


In [4]:
x0 = x[:, 0]  #the first feature
x1 = x[:, 1]    #the second feature

In [5]:
plt.scatter(x_1[:, 0], x_1[:, 1], c='r', marker='^')
plt.scatter(x_0[:, 0], x_0[:, 1], c='b', marker='s')
plt.xlabel("$x_0$")  #first feature
plt.ylabel("$x_1$")  #second feature

#plotting also the decision boundary which is already known
plt.plot(x0, 3-x0, c='y')  #assuming w0 = 1, w1 = 1, b = -3
plt.show() 

In [6]:
#red ones are the positive classes and blue are neg classes

In [7]:
#np.log has base e